feat: add a scriv-based changelog
overhangio/cookiecutter-tutor-plugin pull request #22
Opened 2023-06-09 13:53 UTC by arbrandes

Adds a scriv-based changelog to this repository, modeled after https://github.com/overhangio/tutor-ecommerce/pull/39.

Closes #20.

2023-06-09 15:01 UTC, regisb commented
Thanks for the PR @arbrandes! I don't know whether we need a changelog for this repo, given that we are not making releases. @kdmccormick what do you think?

2023-06-09 16:06 UTC, arbrandes commented
Yeah, when I saw there was no way to get a version, I figure it might defeat the purpose.  🤷

Still, Kyle handed this off to me before going on vacation, so I owed a PR.  Here it is, haha

2023-09-07 16:11 UTC, kdmccormick commented
I think a changelog could still be valuable, assuming it's not hard to set up. Plugin devs would benefit from being able to see how the template changed since the last time they used it.

Would Scriv work without releases, though?

2023-09-08 06:21 UTC, regisb commented
For this particular repo it's probably not worth the effort to use scriv for changelog management. I agree with you @kdmccormick that we could just opt for a simple CHANGELOG.md file.

2023-10-27 09:00 UTC, regisb commented
Can we add a CHANGELOG.md to close this?

2023-10-27 09:01 UTC, regisb requested changes
As discussed, let's just add a single CHANGELOG.md file.

2023-11-06 15:54 UTC, kdmccormick commented
Closed in favor of https://github.com/overhangio/cookiecutter-tutor-plugin/pull/24

2023-11-06 15:54 UTC, closed without merging